import axios from 'axios';

/**
 * Uploads a file directly to ImageKit using signatures generated by the backend.
 * 
 * @param {File} file - The file object to upload.
 * @param {string} folderName - Destination folder in ImageKit (e.g., 'products' or 'prescriptions').
 * @param {function} [onProgress] - Optional callback function to track upload progress (0-100).
 * @returns {Promise<{url: string, fileId: string}>} The uploaded image secure URL and file ID.
 */
export async function uploadToImageKit(file, folderName = 'products', onProgress = null) {
  if (!file) {
    throw new Error("No file provided for upload.");
  }

  // 1. Fetch secure authentication signatures from our backend endpoint
  const authResponse = await fetch('/api/imagekit-auth');
  if (!authResponse.ok) {
    const errorText = await authResponse.text();
    throw new Error(`Failed to obtain ImageKit authentication credentials: ${errorText || authResponse.statusText}`);
  }

  const { token, expire, signature } = await authResponse.json();

  // 2. Validate environment config on client side
  const publicKey = import.meta.env.VITE_IMAGEKIT_PUBLIC_KEY;
  if (!publicKey) {
    throw new Error("VITE_IMAGEKIT_PUBLIC_KEY is not defined in environment variables.");
  }

  // 3. Prepare FormData payload for ImageKit
  const formData = new FormData();
  formData.append('file', file);
  formData.append('fileName', `${Date.now()}-${file.name.replace(/\s+/g, '_')}`);
  formData.append('publicKey', publicKey);
  formData.append('signature', signature);
  formData.append('expire', expire);
  formData.append('token', token);
  formData.append('folder', `/${folderName}`);

  // 4. Post upload directly to ImageKit API with progress tracking
  try {
    const response = await axios.post('https://upload.imagekit.io/api/v1/files/upload', formData, {
      headers: {
        'Content-Type': 'multipart/form-data'
      },
      onUploadProgress: (progressEvent) => {
        if (onProgress && progressEvent.total) {
          const percentCompleted = Math.round((progressEvent.loaded * 100) / progressEvent.total);
          onProgress(percentCompleted);
        }
      }
    });

    if (response.data && response.data.url) {
      return {
        url: response.data.url,
        fileId: response.data.fileId
      };
    } else {
      throw new Error("Upload succeeded but returned invalid response format.");
    }
  } catch (error) {
    if (error.response && error.response.data) {
      throw new Error(error.response.data.message || `ImageKit upload failed: ${error.response.statusText}`);
    }
    throw error;
  }
}
